version: '3.4'

services:
  projekt_lin:
    image: ${DOCKER_REGISTRY-}projektlin
    build:
      context: .
      dockerfile: Projekt LIN/Projekt_LIN/Dockerfile
    depends_on:
     - quickapp.sqldb
     - quickapp.mail

  quickapp.sqldb:
    image: microsoft/mssql-server-linux

  quickapp.mail:
     image: mailhog/mailhog
     ports:
      - "8025:8025"
      - "1125:1025"